NEWS.md
src/eradius_client.erl
src/eradius_node_mon.erl

As the request was decoded on client side before, it is a compatibility layer, which check and save the version of remote eradius and use it on decision to encode request before send it remote or not.

Add backwards compatibility for eradius version < 0.6 for remote calling

---

NEWS.md
src/eradius_lib.erl

seems to have been forgotten when encoding was added

add decoding for integer24 datatype

---

src/eradius_log.erl
test/eradius_logtest.erl
test/readme.md

logging crashed for unknown attributes https://github.com/travelping/eradius/issues/12
this patch should fix this behaviour

Bugfix for Issue #12

---

src/eradius_client.erl
src/eradius_config.erl
src/eradius_proxy.erl
test/eradius_logtest.erl
test/readme.md

For #16.
Proxy is radius handler. You can configure it via handler args, for example:
```erlang
ProxyConfig = [{default_route, {{127, 0, 0, 1}, 1813, <<"default_secret">>}}, 
{options, [{type, realm}, {strip, true}, {separator, "@"}]},
{routes, [{"test", {{127, 0, 0, 1}, 1815, <<"secret">>}}]}
],
....
{proxy, [
{ {eradius_proxy, "proxy", ProxyConfig }, [{"127.0.0.1", <<"proxy_secret">>}] }
]}
```
`default_route` - ip, port and secret for home server, `routes` - list of servers for routing. `options` - how to resolve route

Add possibility to proxy radius requests

---

src/eradius_config.erl
src/eradius_server.erl
test/eradius_config_SUITE.erl
test/eradius_logtest.erl

Relate to #23 
You can use ip ranges in this format `x.x.x.x/m`, for example:
```erlang
{root, [
{ {handler, "NAS", []}, [ {"10.18.14.2/30", <<"secret2">>, [{group, "NodeGroup"}]} ] }
]}]
```

Add IP ranges for NAS clients

---

src/eradius_log.erl
src/eradius_server.erl

the meta fields didn't contain the request-type and request-id, making it unnecessary complicated to filter for these information

added request-type and -id to request logging

---

.travis.yml
src/eradius_counter.erl
src/eradius_counter_aggregator.erl
src/eradius_lib.erl
src/eradius_proxy.erl
src/eradius_server.erl
test/eradius_client_SUITE.erl
tetrapak/config.ini

Add OTP 18

---

src/eradius_client.erl
src/eradius_lib.erl

Accounting, Disconnect and CoA Requests start with authenticator
consiting of 16 binary zeros, the encoder will use that to calculate
the correct authenticator.

properly initialize the authenticator

---

include/eradius_lib.hrl
include/metrics.hrl
src/eradius.app.src
src/eradius.erl
src/eradius_client.erl
src/eradius_client_socket.erl
src/eradius_counter.erl
src/eradius_metrics.erl
src/eradius_proxy.erl
src/eradius_server.erl
src/eradius_server_mon.erl
test/eradius_client_SUITE.erl
test/eradius_logtest.erl

This commit provides mostly two things:
First of all it provides client side metrics. We already have some client
side metrics which are were added in the 80a4204 commit (Initial support for
exometer metrics), but they represent only general metrics, like amount of
socket errors, count of client requests and etc. Besides these general metrics
we can calculate more specific metrics like count of the 'access requests',
count of the 'accept responses' and etc.
The second change that now eradius environment provides new: 'metrics' configuration
which just represents a list of metric types which are will be enabled after start.

eradius: add client metrics

---

src/eradius_server_mon.erl
test/eradius_config_SUITE.erl

Use `ets:delete_object/2` instead of `ets:delete/2`
Add test for this case

Fix removing nas from nas_tab when reconfiguring

---

src/eradius_metrics.erl

The exometer:info() returns undefined if metric is not found. So,
we need to check this value instead of empty list for newly created
metric.

Fix uptime metric

---

src/eradius_metrics.erl

No need to convert `ServerName` to atom from binary because it is atom already.

Fix server uptime metric

---

src/eradius.app.src
src/eradius_server.erl

* make possible to disable retransmittion by setting resend_timeout to 0
* set default retransmittion time to 2 sec (https://tools.ietf.org/html/rfc5080#section-2.2.1)
* default disable file logging
* set default client_ports to 100 to allow more parallel sockets in the client

performance tuning

---

rebar_plugins/eradius_compile_dicts_plugin.erl
tetrapak/eradius_compile_dicts.erl

* some dictionaries have spetial attribute names like "Altiga_L2TP_Min_Authentication_G/U" in altiga that was transformed wrong

define the macro name as atom

---

src/eradius_client.erl

Because it is a `\8` function and not `\6` as before

Fix eradius_client:send_remote_request_loop call in spawn

---

rebar_plugins/eradius_compile_dicts_plugin.erl

The alcatel.sr dictionary contains two dots. Without the
global option to re:replace, only the first dot is replaced.
Fixes #77

replace all dots (.) in dictionaries with underscores (_)

---

src/eradius_client.erl
src/eradius_proxy.erl

I was experimenting with dialyzer and found some "error" in specs. 
The scope of changes:
client:
* Fix spec for `send_request/3`. In success it alway returns `{ok, binary(), eradius_lib:authenticator()}`.
* Remove `proceed_response(Request, Value, Peer, TS1, undefined)`. Because `MetricsInfo` can't be `undefined`.
* Use `null` as possible type for socket_ip. Because `null` is incorrect value for `inet:ip_address()`
proxy:
* Fix spec for `validate_route/1`
* Fix spec for `new_request/3`.Username should be `undefined` or `binary()`
* Fix spec for `get_key/4`. It may return `not_found`.

Dialyzer client and proxy fixes

---

dicts_compiler.erl
rebar.config
src/eradius_lib.erl

Previously we used rebar plugin to build Radius dictionaries but it only works with rebar2.
Using hooks allows us easy change to rebar3.

Use hooks to compile and clean Radius dictionaries

---

priv/dictionaries/dictionary

The actual en/decoder functions are already there. Just fix the
type declaration in the dictionary.

proper type for RFC 3162 IPv6 attributes

---

.travis.yml
rebar.config
rebar.config.script

Also lager was updated to build with Erlang 19.
Note that we don't send coveralls data via rebar3 because cover.spec is
not supported now.

Increase Erlang versions in Travis and add rebar3 env

---

src/eradius_proxy.erl

In this case default route will be used.

Fix crash eradius_proxy when User-Name is empty

---

src/eradius.app.src
src/eradius_client_socket.erl
src/eradius_server.erl

With high amount of udp packets if you can't process all of the receive packets,
kernel will drop new incoming packets if the socket receive buffer is full.
Using `recbuf` option it's possible to configure the socket receive buffer size.
The kernel options `net.core.rmem_max` and `net.core.netdev_max_backlog` should
also be configured.

make maximum socket receive buffer configurable

---

rebar.config
src/eradius_lib.erl

as it is deprecated and will be removed.

use crypto:strong_rand_bytes/1 instead of crypto:rand_bytes/1

---

dicts_compiler.erl
priv/dictionaries/dictionary.ascend
priv/dictionaries/dictionary.erx
priv/dictionaries/dictionary.nomadix
priv/dictionaries/dictionary.redback

To get rid annoying compile warning like this:
missing: "Framed-Compression"

Fix dictionary compiler to build basic dictionary first

---

priv/dictionaries/dictionary.travelping

May be used to share some OpenTracing id between components.

Add TP-Trace-Id to Travelping dictionary

---

src/eradius_lib.erl
test/eradius_lib_SUITE.erl

Before both encoding and decoding were broken by wrong bit syntax.

Fix ipv6prefix coding

---

src/eradius_config.erl
src/eradius_proxy.erl
test/eradius_proxy_SUITE.erl

during making decision where to send a request.
From this moment, proxy configuration contains not just a realm/prefix
string, but regular expression.
For example:
{routes,
[{"^test-",  {{127, 0, 0, 1}, 1812, <<"secret1">>}},
{"*_test$", {{127, 0, 0, 2}, 1813, <<"secret2">>}}]}
Requests where realm will be started from `test-`, will
be routed to the first `127.0.0.1:1812` relay.
Requests where realm will be ends with `_test`, will be
routed to the second `127.0.0.1:1813` relay.

match relays with a regular expression

---

src/eradius_client.erl
src/eradius_proxy.erl
test/eradius_proxy_SUITE.erl

With the following defaults timeout = 5000 and retries = 1.

timeout and retries configuration options for eradius_proxy

---

rebar.config
test/eradius_client_SUITE.erl

* test test profile which allows to use export_all without errors
* `random` -> `rand`

Fix warning when run common test suites

---

rebar.config
rebar.lock

Because we only need it to run `ct`

Move meck to the test profile

---

src/eradius_proxy.erl

Fix improper edoc quoting. 
Before this patch:
```
Auriga ~/work/eradius (git::tags/0.8.7): /usr/bin/rebar doc -vv
...
==> eradius (doc)
DEBUG: "src/eradius_proxy.erl" is more recent than "doc/edoc-info": {{2017,10,30},{18,20,12}} > {{2017,10,30},
{18,17,58}}
INFO:  Regenerating edocs for eradius
./src/eradius_proxy.erl, in module header: at line 7: ```-quote ended unexpectedly at line 15
edoc: skipping source file './src/eradius_proxy.erl': {'EXIT',error}.
edoc: error in doclet 'edoc_doclet': {'EXIT',error}.
ERROR: doc failed while processing /home/petro/work/eradius: {'EXIT',error}
Auriga ~/work/eradius (git::tags/0.8.7): 
```
With this patch:
```
Auriga ~/work/eradius (git::proper_edoc_quoting): /usr/bin/rebar doc -vv
...
==> eradius (doc)
DEBUG: "src/eradius_proxy.erl" is more recent …

Proper quoting in doclet

---

src/eradius_server_mon.erl

In case if NAS declared with 0.0.0.0 as source IP, eradius server
accepts request without checking real IP.

Allow 0.0.0.0 as NAS IP to avoid checking source IP

---

dicts_compiler.erl
priv/dictionaries/dictionary.alcatel
priv/dictionaries/dictionary.redback
src/eradius_dict.erl

Hello All!
Please take a look at the feature I've backported from my fork of eradius (I switched to yours and abandoned mine). This PR allows us to sync dictionaries across all consumers w/o changing anything.
For example, some RADIUS-clients parse $INCLUDE directive so one can only set /usr/share/_some_app_name_/dictionary and client library will do the rest. Unfortunately with this RADIUS-library you have to manually provide a list of dictionaries to fetch. Not anymore! Just rsync the same dictionaries, regenerate *.map and *.hrl files, recompile eradius and that's all!
I'm not expecting that you'll merge it blindly in a seconds, so any critics is more than welcome.
I have some more features in my TODO list, since I'm using dictionaries from @FreeRADIUS, but I'd like to start from …

RFE: parse $INCLUDE directive in priv/dictionaries/dictionary* files

---

priv/dictionaries/dictionary.bay
src/eradius_dict.erl
src/eradius_lib.erl
src/eradius_log.erl
test/eradius_lib_SUITE.erl

Allow ets to store different elements with a same id and allow to select the type needed between attribute | vendor | value. Related to #130

 Fix dictionary collisions

---

src/eradius_client.erl

This simple example shows the difference:
> Cmd = 'request'.
> IP = this_is_not_ip.
> Cmd == 'request' orelse Cmd == 'accreq' andalso is_tuple(IP).
true
> (Cmd == 'request' orelse Cmd == 'accreq') andalso is_tuple(IP).
false
This commit uses the proper priority for logical operators as in the
second example.

Fix GOOD_CMD guard to have ability to combine it with others guards

---

src/eradius_client.erl
test/eradius_client_SUITE.erl
test/eradius_test_handler.erl

A domain name will be resolved with using `inet` module. In case of
the answer has more that one IP, the IP will be selected randomly.

Resolve domain name during send request on client

---

CHANGELOG.md

We bump the minor number because dictionary fix was made. There was a collision during processing dictionaries, see #130. 
Now `eradius_dict` has two version of `lookup` funciton:
```
-spec lookup(attribute_id() | value_id()) -> 
[#attribute{} | #value{} | #vendor{}].
```
and the new helper to parametrize type:
```
-spec lookup(attribute | vendor | value, attribute_id() | value_id() | vendor_id()) -> 
false | #attribute{} | #value{} | #vendor{}.
```
Also, since this version `eradius_client` can use domain names for destinations:
```
eradius_client:send_request({"aaa.example.com", 1812, "secret"}, #radius_request{cmd = request}, [])
```

Version 0.9.0

---

include/eradius_metrics.hrl

Because the default value provided by exometer is 40000 which is high
for big amount of histograms, see Feuerlabs/exometer_core#100
We set it to 233 according to default value described in Erlang Efficiency Guide.

Set min_heap_size to default value for exometer histograms

---

src/eradius_auth.erl

In some cases it may return just `false` instead of tuple

Fix eradius_auth:check_password/2 specification

---

dicts_compiler.erl

Sometimes you'd better look at the dicts_compiler's output. So why not make it human-readable?
Note the length-prefixed ~110p and ~100p. This is done to avoid line wrapping.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

Make map-files human-readable

---

applications/eradius_prometheus_collector/src/eradius_prometheus_collector.erl

as it could be useful to fetch counters and provide stats from outside to avoid multiple accessing of eradius_counter ets table when we need to fetch multiple counters.

export eradius_prometheus_collector:fetch_counter/3

---

src/eradius.app.src
src/eradius_counter_aggregator.erl

In a case of enabled eradius_counter_aggregator - it collects metrics
values by heartbeat timeout. Since f68fdbfe57 we have added client metrics,
so not only nas_counter{} record could be passed to the
eradius_counter_aggregator:update_stats/1 but also client_counter{}. In this
case there will be function clause error as right now update_stats/1 accepts
only nas_counter{} parameter.
This commit fixes this by adding new clause to accept client_counter{} record
in eradius_counter_aggregator:update_stats/1

fix collecting of metrics in eradius_counter_aggregator

---

src/eradius_client.erl
src/eradius_proxy.erl
test/eradius_client_SUITE.erl
test/eradius_proxy_SUITE.erl
test/eradius_test_handler.erl

This commit adds support for fail-over. Set of secondary RADIUS servers could be passed to the RADIUS client API eradius_client:send_request/3 via options or to RADIUS proxy via configuration.
If the response wasn't received after a number of requests specified by `retries` configuration option for the given RADIUS server - such RADIUS servers will be marked as non-active and RADIUS requests will not be sent for such `non-active` RADIUS servers. The new configuration option is represented as well in this PR - `eradius.unreachable_timeout`. This option specifies how long such `non-active` RADIUS servers should be considered as unreachable. Such `non-active` RADIUS server will be marked as active and returned to the servers pool after the timeout specified as a value of the …

add support for failover to RADIUS client

---

rebar.config

* `meck` - https://github.com/eproxus/meck/blob/master/CHANGELOG.md
* Due to `eradius` description:
```
Erlang Version Support
All minor version of the current major release and the highest minor version of the previous major release will be supported.  
At the moment this means OTP 21.3, OTP 22.x and OTP 23.x are supported. OTP versions before 21.0 do not work due the use of logger.  
When in doubt check the otp_release section in .travis.yml for tested versions.
```
and due to fact that `meck` have logic for checking release version with using both syntaxes, no make sense include `stacktrace_compat` and follow the update of this library at all, by this reason I suppose make sense remove `stacktrace_compat` from `eradius`

Update deps: meck, stacktrace_compat

---

src/eradius.app.src
test/eradius_metrics_SUITE.erl
test/eradius_test_handler.erl

Remove unused config option `metrics`

Remove metrics env what was use for exameter

---

rebar.config
src/eradius_counter.erl

When a RADIUS request comes to eradius or we try to send a request from it - new histogram metric could be created. There could be a situation when a couple of RADIUS requests with the same name and similar labels come to eradius which may lead to crash because of races during creation of prometheus metric.
This commit replaces prometheus_histogram:new/1 with prometheus_histogram:declare/1 API as the first one throws an exception in a case of metric already exists.

use prometheus_histogram:declare/1 instead prometheus_histogram:new/1

---

src/eradius_proxy.erl

as that may lead to a badmatch error in a case when this configuration option
is not defined

set servers_pool to empty list by default

---

src/eradius_proxy.erl

As application:get_env/3 returns Val but not {ok, Val}

fix getting of servers_pools from configuration in eradius_proxy handler

---

rebar.config.script

The HAVE_PERSISTENT_TERM option was used to build eradiusd with
persistent_term support. But it was lost in the 9dccab38040 commit.
This commit returns it back.

fix building of eradius with persistent_term

---

src/eradius_counter.erl

Previously we used two operations to update a RADIUS counter metric:
ets:lookup/2 and ets:insert/2. This commit replaces these operations
with one - ets:update_counter/4 which should be more efficient.

Use ets:update_counter to update RADIUS metrics

---

src/eradius_client.erl
test/eradius_metrics_SUITE.erl

We are using ets:match_spec_run/2 to go over given attributes to
match type of RADIUS Accounting request to update a certain metric by
RADIUS Accounting type.
The issue is that we may get RADIUS attributes during sending of a RADIUS
request in two following formats:
* [{AttrId, Value}, ...]
* [#attribute{}, ....]
But only the first one could be matched in ets:match_spec_run/2. Thus if
RADIUS attributes will be given in the second format - a RADIUS Accounting
client metric will not be updated.
This commit fixes this situation.

Fix gathering of RADIUS Accounting metrics

---

rebar.config
src/eradius_client.erl
src/eradius_counter.erl
src/eradius_proxy.erl
test/eradius_client_SUITE.erl
test/eradius_metrics_SUITE.erl
test/eradius_test_handler.erl

**Backward compatibility is preserved and new functionality will be used only in a case when fail-over is enabled.**
This PR contains following two changes:
The first commit improves fail-over mechansim.
When RADIUS client process is started it collects all secondary RADIUS servers from RADIUS server pools into ets table to use them for fail-over. The commit adds primary servers to this ets table as well. We need this to avoid following situation: A primary 
RADIUS server was used but eradius client failed to send requests there by some reasons. So such RADIUS server will be marked as inactive for a some configurable period of time and secondary RADIUS server will be used.
The issue is that eradius client could be used again with the primary server while it is still in inactive state. …

Add server_status metric

---

METRICS.md
README.md
src/eradius.app.src
src/eradius_client.erl
test/eradius_metrics_SUITE.erl

This commits adds new configuration option - `server_status_metrics_enabled` to
enable new RADIUS server status metrics.
This was done to avoid situation when eradius is used without prometheus library
so creation/usage of this metric will not be crashed at startup of eradius
application.
The default value of the new configuration option is set to `false` to preserve
backward compatibility.

Make server status metrics optional

---

src/eradius_client.erl

When eradius sets a server status metric to 'active' state for a
certain server - other servers are marked as inactive.
The issue was that only current server was set to inactive only
current server because of wrong match. This commit fixes that.

Fix updating of server status metric

---

src/eradius_client.erl
src/eradius_counter.erl
src/eradius_server.erl

Previously milliseconds values were used which leads to wrong
behaviour of prometheus histograms as it expects to get observations
in native time units

Use native time unit for prometheus histograms

---

src/eradius_client.erl
test/eradius_test_handler.erl

RADIUS client API allows to pass list of failover servers. Active
failover servers are stored within internal ets table as list of
IPs/ports. So if a request will fail for a primary RADIUS server -
eradius will try to find active failover server based on passed
list and data from the ets table.
The issue is that failover servers could be passed to the RADIUS
client as list of Hosts/Ports instead of IPs/Ports. This commit
adds resolving of given failover servers hostnames so if list
of failover RADIUS servers contains hostnames eradius client still
could find an active server.

Resolve a failover RADIUS server hostname if need

---

priv/dictionaries/dictionary.compat

to avoid warnings during compilation

remove duplicated Login-Host attribute from dictionary.compat

---

src/eradius_client.erl
src/eradius_server.erl

This commit provides the following improvements for the logging:
1. Switch to info from debug in the logging messages for the incoming requests and outgoing responses. There is no big sense in these messages anyway if everything is normal but more useful during debugging process.
2. Add logging to the RADIUS client if hostname can not be resolved. The log messages are added only to the place where we handle secondary/failover RADIUS servers to not spam with such messages.
3. Remove additional log message for the outgoing response. We already have such message from the point 1 which has everything what the removed message had except the RADIUS server name.

Improve logging in RADIUS server and client

---

src/eradius_client.erl

The error logging messages contained 'request' while the error was based on the failed decoding of the response.
This commit fixes this confusing logs.

Fix logging for the errors related to decoding of response
