README.md
The renaming questions can be removed for now!
=> fixed link in README and removed renaming question

.gitignore, README_eradius_journal.adoc, example.config, src/eradius.app.src, src/eradius_client.erl, src/eradius_log.erl, src/eradius_server.erl, test/eradius_logtest.erl, test/readme.md, tetrapak/config.ini, tetrapak/dev.config
added informational lager logging
=> Infotojournal

include/eradius_lib.hrl, src/eradius.erl, src/eradius_client.erl, src/eradius_dict.erl, src/eradius_log.erl, src/eradius_server.erl, src/eradius_server_mon.erl, src/eradius_server_sup.erl
switching from errorlogger to lager
=> Errortolager

NEWS.md, priv/dictionaries/dictionary.travelping
add vendor values for Framed-Protocol and Service-Type
=> add vendor values for Framed-Protocol and Service-Type

src/eradius_config.erl, test/eradius_logtest.erl
You can use validate_arguments/1 in handler module
#20
=> Possibility checking of arguments on start

.travis.yml, rebar.config
I'm going to fix common test later
=> Add Travis

src/eradius.erl, src/eradius_log.erl, test/eradius_config_SUITE.erl
=> Add possibility to reconfigure logger

src/eradius_log.erl
Additionals for #36. 
This fixes problem with if logging is active and there was problem with opening log file.
=> Additionals for previous PR about reconfigure logger

src/eradius_config.erl, test/eradius_config_SUITE.erl
=> Fix ip4_address format for NAS IP

src/eradius_lib.erl
The maximum  RADIUS attribute payload length is 255 octets, ake sure
the encoded attrbiute fits that size, throw badarg [Type, Value] if
not.
=> ensure the encoded values do not exceed the maximum attribute length

src/eradius_lib.erl
[WiP] as it doesn't brought any effect on opposite side.
=> Fix coa and disconect requests

include/metrics.hrl, src/eradius_metrics.erl, src/eradius_server.erl
The main chages are:
* added 'max' datapoint for client metrics
* add handle_request_time server metric
=> Metrics improvements

src/eradius_client.erl, src/eradius_metrics.erl, test/eradius_client_SUITE.erl
=> check already subscribed clients in the client state

src/eradius_proxy.erl
erproxyadius_client -> eradius_client
=> Fix type name typo in eradius_proxy

src/eradius_lib.erl
The decoder has to use the authenticator from the corresponding
request and not from the response. Pass the request authenticator
through the decoder state to avoid adding it to the radius record.
Also, MD5 generation for values > 16 bytes, is different for encoding
and decoding.
=> fix decoder for salt encrypted fields

rebar.config, src/eradius_log.erl
Additionally lager updated to 3.2.2 which contains bug fixes for log rotation.
=> add accouting status type and class to logs

src/eradius_server.erl
Now it should put radius attributes to journal meta fields instead of
writing them into message attribute.
=> improve logging timeout error message

include/eradius_metrics.hrl, src/eradius_client.erl, src/eradius_client_socket.erl, src/eradius_lib.erl, src/eradius_proxy.erl, src/eradius_server.erl, src/eradius_server_mon.erl, src/eradius_server_sup.erl
* add authentication of response
* move authentication logic from eradius_client into the eradius_lib
* extend logging
* add metric for discarded packets on the client
=> rework RADIUS authentication

src/eradius_server.erl
A transaction handler doesn't need to send `free` message to inform
server about deleting because the server can do it by `EXIT` message
which will be sent when the transaction is finished.
Also, instead of ets:match_delete/2 use ets:delete/2 and ets:take/2
and additional insert with {HandlerPid, ReqKey}
=> Simplify the server freeing TX mechanism

.travis.yml, src/eradius_lib.erl
* crypto:random_uniform/2 -> rand:uniform/1
* remove export_all in eradius_lib
=> Fix compile warnings for OTP20

rebar.config
PR to resolve issue #102 on Windows
=> Fix compile error on Windows. Fix for Issue #102

src/eradius_proxy.erl
in send_to_server(). This may occur in a case when default_route
was not configured and no suitable routes found.
=> do not send RADIUS request if a suitable route was not found

METRICS.md, README.md
This files describes all existing metrics in eradius.
=> Add METRICS.md

src/eradius_client.erl, src/eradius_client_socket.erl, src/eradius_node_mon.erl, test/eradius_client_SUITE.erl, test/eradius_client_socket_test.erl
Since OTP 18 maps work faster that dict.
=> Reworks dicts to maps in client and node_mon

src/eradius_proxy.erl, test/eradius_proxy_SUITE.erl
=> domain names should pass validation in proxy

METRICS.md
see https://github.com/travelping/eradius/blob/master/src/eradius_client.erl#L134
=> dropped packets metric is a response metric

CHANGELOG.md, src/eradius_server.erl
in addition eradius version is bumped to `1.0.1`
=> fix logging messages which contains meta information

src/eradius_dict.erl, test/eradius_lib_SUITE.erl
* Reworked the logic to remove the dictionaries for the existing logic
* Reworked of PR https://github.com/travelping/eradius/pull/146 for the `persistent_term use`
=> Rework of add dictionary unloading functionality

rebar.config, src/eradius.app.src
- Added plugin `rebar3_hex`
- Added `applications` missed folder for correct pushing to `hex.pm`
=> Update hex package

src/eradius.app.src
Started use [SemVer](https://semver.org/) and keep one `vsn` style.
=> Added semver

applications/eradius_prometheus_collector/rebar.config
* Started used 'master' of 'prometheus' with changes based on speed up work
=> Start use 'master' of prometheus

.github/workflows/main.yml
Add button workflow for forks branchesI. More info https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> Added workflow_dispatch to CI

.github/workflows/hex.yaml
The current fix is related to the https://github.com/actions/runner/issues/2033
=> [GH actions] add work around for permission issue
